name: Compile C++ code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile code
      run: |
        g++ src/main.cpp -o main

    - name: Show compiled file
      run: ls -l main
