name: Compile C++ code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Boost libraries
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev

    - name: Compile code
      run: |
        g++ src/main.cpp -o main -lboost_system

    - name: Show compiled file
      run: ls -l main
